package com.oms.service.domain.enums;

public enum StateOrder {
	PENDING,
	SUCCESS,
	PROCESSING,
	DELIVERING,
	COMPLETED,
	CANCELED,
	RETURNED,
	DELETED,
	PAYMENT_SUCCESS,
	PAYMENT_FAILED,
	PAYMENT_FAILED_AND_REFUND,
	PAYMENT_FAILED_AND_REFUND_SUCCESS,
	PAYMENT_FAILED_AND_REFUND_FAILED
}
